name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'docs(') && !contains(github.event.head_commit.message, 'style(') && !contains(github.event.head_commit.message, 'refactor(')"
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
        arch:
          - x86
        include:
          - arch: x86
            platform: Win32
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Install Premake5
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Generate project files
        run: premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{matrix.configuration}} ${{matrix.arch}} binaries
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} build/xylazine.sln

      - name: Upload ${{matrix.configuration}} ${{matrix.arch}} Binary
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Xylazine.exe - ${{matrix.configuration}} ${{matrix.arch}}
          path: |
            build/bin/${{matrix.configuration}}-${{matrix.arch}}/xylazine.exe

      - name: Upload ${{matrix.configuration}} ${{matrix.arch}} Symbols
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Xylazine.pdb - ${{matrix.configuration}} ${{matrix.arch}}
          path: |
            build/bin/${{matrix.configuration}}-${{matrix.arch}}/xylazine.pdb